const {JSDOM}=require('jsdom');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const web=path.resolve(process.argv[2]||'web');
const sample=JSON.parse(fs.readFileSync(path.join(web,'sample-result.json')));
const dom=new JSDOM(fs.readFileSync(path.join(web,'index.html'),'utf8'),{url:'http://localhost:8016',runScripts:'outside-only'});
const w=dom.window,$=id=>w.document.getElementById(id);
let current,download;
w.fetch=async()=>({ok:true,json:async()=>structuredClone(sample)});
w.Worker=class{constructor(){current=this;}postMessage(data){this.request=data;}terminate(){this.terminated=true;}};
w.URL.createObjectURL=blob=>{download=blob;return 'blob:sample';};w.URL.revokeObjectURL=()=>{};
w.Blob=Blob;w.HTMLAnchorElement.prototype.click=function(){};
(async()=>{
 const source=fs.readFileSync(path.join(web,'terminal.js'),'utf8').replaceAll('import.meta.url',"'http://localhost:8016/terminal.js'");
 await w.eval('(async()=>{'+source+'\n})()');
 assert.equal($('trade-count').textContent,String(sample.metrics.trade_count));
 w.document.querySelector('[data-view="method"]').click();
 assert.equal(w.document.querySelector('[data-panel="method"]').hidden,false,'Methodology click works');
 w.document.querySelector('[data-view="trades"]').click();
 $('next-page').click();assert.match($('ledger-page-label').textContent,/Page 2/);
 $('ledger-filter').value='momentum_breakout';$('ledger-filter').dispatchEvent(new w.Event('change'));
 assert.equal($('ledger-rows').querySelectorAll('tr').length,2);
 $('commission').value='3.5';$('commission').dispatchEvent(new w.Event('change'));
 assert.match($('run-state').textContent,/Settings changed/);
 $('run-button').click();
 assert.equal(current.request.payload.settings.commission_per_contract,3.5);
 assert.equal($('run-button').disabled,true);
 $('cancel-button').click();assert.equal(current.terminated,true);assert.match($('run-state').textContent,/cancelled/);
 $('run-button').click();current.onmessage({data:{id:current.request.id,type:'error',message:'Invalid input test'}});
 assert.equal($('error-banner').textContent,'Invalid input test');
 assert.equal($('trade-count').textContent,String(sample.metrics.trade_count));
 $('run-button').click();const empty=structuredClone(sample);empty.trades=[];empty.metrics={...empty.metrics,trade_count:0,net_pnl:0,gross_pnl:0,costs:0,max_drawdown:0};empty.equity=[{timestamp:sample.dataset.start,balance:50000,drawdown:0}];
 current.onmessage({data:{id:current.request.id,type:'result',result:empty}});
 assert.match($('price-chart').textContent,/No completed trades/);assert.equal($('trade-evidence').innerHTML,'');
 $('export-report').click();assert.equal(JSON.parse(await download.text()).metrics.trade_count,0);
 $('sample-download').click();assert.match(await download.text(),/^timestamp,open,high,low,close,volume/);
 console.log('UI checks passed: sample render, navigation, pagination, filter, settings, worker payload, cancellation, error preservation, zero-trade state, report and CSV exports.');
 dom.window.close();
})().catch(error=>{console.error(error);dom.window.close();process.exitCode=1;});

